version: "3.7"

services:

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/lib/nginx/ssl/djpass.crt:/etc/nginx/ssl/djpass.crt
      - /var/lib/nginx/ssl/djpass.key:/etc/nginx/ssl/djpass.key
      - /var/lib/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      djpass_compose_net:
        ipv4_address: 10.0.1.2



  django:
    image: jackuna/djpass:v1
    expose:
      - "9090"
    networks:
      djpass_compose_net:
        ipv4_address: 10.0.1.3



networks:
  djpass_compose_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
